/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Client.Cliente;
import Models.Messages.Message;
import Models.Tablero.Board;
import Models.Tablero.Pieza;

import java.awt.Point;
import java.util.ArrayList;
import java.util.Arrays;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 23jic
 */
public class ClientFrame extends BoardFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientFrame.class.getName());
    private Cliente cliente;
    
    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        
        initComponents();
        cliente = new Cliente(this);
        jTextArea1.append(cliente.getNombre());
        jButton1.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonPieza = new javax.swing.JButton();
        labelDado1 = new javax.swing.JLabel();
        labelDado2 = new javax.swing.JLabel();
        labelRDado1 = new javax.swing.JLabel();
        labelRDado2 = new javax.swing.JLabel();
        labelDadoTotal = new javax.swing.JLabel();
        labelRDadoTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelDado3 = new javax.swing.JLabel();
        labelDado4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaChat = new javax.swing.JTextArea();
        labelChat = new javax.swing.JLabel();
        textFieldChat = new javax.swing.JTextField();
        buttonEnviarChat = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jButton1.setText("Tirar dados");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButtonPieza.setText("Seleccionar pieza");
        jButtonPieza.addActionListener(this::jButtonPiezaActionPerformed);

        labelDado1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelDado1.setForeground(new java.awt.Color(0, 0, 0));
        labelDado1.setText("Dado 1:");

        labelDado2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelDado2.setForeground(new java.awt.Color(0, 0, 0));
        labelDado2.setText("Dado 2:");

        labelRDado1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelRDado1.setForeground(new java.awt.Color(0, 0, 0));
        labelRDado1.setText("0");

        labelRDado2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelRDado2.setForeground(new java.awt.Color(0, 0, 0));
        labelRDado2.setText("0");

        labelDadoTotal.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelDadoTotal.setForeground(new java.awt.Color(0, 0, 0));
        labelDadoTotal.setText("Total:");

        labelRDadoTotal.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelRDadoTotal.setForeground(new java.awt.Color(0, 0, 0));
        labelRDadoTotal.setText("0");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.black));
        jScrollPane2.setViewportView(jTextArea1);

        labelDado3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelDado3.setForeground(new java.awt.Color(0, 0, 0));
        labelDado3.setText("Comodín");

        labelDado4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        labelDado4.setForeground(new java.awt.Color(0, 0, 0));
        labelDado4.setText("Juego");

        jLabel2.setBackground(new java.awt.Color(0, 255, 51));
        jLabel2.setText("   ");
        jLabel2.setMaximumSize(new java.awt.Dimension(15, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(15, 15));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(15, 15));

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("   ");
        jLabel3.setMaximumSize(new java.awt.Dimension(15, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(15, 15));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPieza))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDado4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelDado3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDado2)
                            .addComponent(labelDado1)
                            .addComponent(labelDadoTotal))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelRDado2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(labelRDado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRDadoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDado1)
                    .addComponent(labelRDado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDado2)
                    .addComponent(labelRDado2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDadoTotal)
                    .addComponent(labelRDadoTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDado3)
                    .addComponent(labelDado4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonPieza)))
        );

        textAreaChat.setEditable(false);
        textAreaChat.setColumns(20);
        textAreaChat.setRows(5);
        jScrollPane1.setViewportView(textAreaChat);

        labelChat.setFont(new java.awt.Font("Franklin Gothic Book", 3, 18)); // NOI18N
        labelChat.setText("Chat");

        textFieldChat.setToolTipText("Escribir mensaje");

        buttonEnviarChat.setText("Enviar");
        buttonEnviarChat.addActionListener(this::buttonEnviarChatActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelChat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textFieldChat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEnviarChat)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(labelChat)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldChat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEnviarChat))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregarMensaje(cliente.getLog() + "\n\n");
        if (!cliente.isTurnoActual()) {
            JOptionPane.showMessageDialog(this, "No es tu turno aún. Espera a que el servidor te notifique.");
            return;
        }
        if (cliente.getPlayer().getTurnosPendientes() != 0){
            actualizarEstadoBotonTirada(false);
            JOptionPane.showMessageDialog(this, "Tiene turnos pendientes, no puede jugar este turno");
            cliente.getPlayer().setTurnosPendientes(cliente.getPlayer().getTurnosPendientes()-1);
        }
        else{
            //Revisar si falló el último turno en el juego y repetir
            if (!cliente.isUltimoJuegoGanado()){
                cliente.getPantalla().mostrarMensaje("Debe completar el juego del turno anterior para poder lanzar los dados.");
                actualizarEstadoBotonTirada(false);
                cliente.checkCasillaActual();
            }
            if (cliente.isUltimoJuegoGanado()){
                cliente.realizarLanzamientoDeDados();
                if (cliente.getPlayer().getPieza().getLabel() == null){
                    dibujarPiezaPropia(cliente.getPlayer().getPosicion(), cliente.getPlayer().getPieza(), cliente.getNombre());
                } else{
                    moverPiezaPropiaExistente(cliente.getPlayer().getPosicion(), cliente.getPlayer().getPieza(), cliente.getNombre());
                }
                if (cliente.checkCasillaFinal()){
                    mostrarMensaje("Ha llegado a la última casilla y ha ganado!");
                    return;
                }
                actualizarEstadoBotonTirada(false);
                cliente.checkCasillaActual();
            }
            
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiezaActionPerformed
        
        obtenerPieza();
        
    }//GEN-LAST:event_jButtonPiezaActionPerformed

    private void buttonEnviarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarChatActionPerformed
        
        enviarMensajeChat();
    }//GEN-LAST:event_buttonEnviarChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnviarChat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPieza;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelChat;
    private javax.swing.JLabel labelDado1;
    private javax.swing.JLabel labelDado2;
    private javax.swing.JLabel labelDado3;
    private javax.swing.JLabel labelDado4;
    private javax.swing.JLabel labelDadoTotal;
    private javax.swing.JLabel labelRDado1;
    private javax.swing.JLabel labelRDado2;
    private javax.swing.JLabel labelRDadoTotal;
    private javax.swing.JTextArea textAreaChat;
    private javax.swing.JTextField textFieldChat;
    // End of variables declaration//GEN-END:variables


    public String obtenerNombre(){
        String name = JOptionPane.showInputDialog("Digite su nick:");
        return name;
    }

    public void obtenerPieza(){
        String nombrePieza = (String) JOptionPane.showInputDialog(null, "Escoja una pieza para jugar:", "Pieza", JOptionPane.QUESTION_MESSAGE, null, cliente.obtenerStringPiezasDisponibles(), cliente.obtenerStringPiezasDisponibles()[0]);
        if (nombrePieza != null){
            Pieza piezaSeleccionada = cliente.obtenerPiezaDesdeString(nombrePieza);
            if (cliente.getPlayer().getPieza() != null){
                //Pieza vuelve a ser disponible
                cliente.getPlayer().getPieza().setDisponible(true);
                cliente.habilitarPiezaSeleccionada();
            }
            cliente.getPlayer().setPieza(piezaSeleccionada);
            cliente.deshabilitarPiezaSeleccionada();
            cliente.enviarPiezasDisponiblesActualizadas();
            cliente.enviarMensajeATodos("El jugador " + cliente.getNombre() + " ha escogido la pieza " + cliente.getPlayer().getPieza().getNombre());
        }
        
    }

    public String obtenerOtroJugador(){
        String nombreJugador = "";
        if (cliente.getNombresOtrosPlayers().size()>0){
            Object[] nombresJugadores = cliente.getNombresOtrosPlayers().toArray();
            nombreJugador = (String) JOptionPane.showInputDialog(null, "Escoja un jugador:", "Jugador", JOptionPane.QUESTION_MESSAGE, null, nombresJugadores, nombresJugadores[0]);
        }
        else{
            agregarMensaje("No hay otros jugadores");
        }
        
        return nombreJugador;
    }

    public int obtenerCasillasCola(){
        int intCantCasillas = 0;
        String[] opciones = {"-3","-2","-1","0","1","2","3"};
        String cantCasillas = (String) JOptionPane.showInputDialog(null, "Escoja una pieza para jugar:", "Pieza", JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if (cantCasillas != null){
            intCantCasillas = Integer.parseInt(cantCasillas);
        }
        return intCantCasillas;
    }
    
    public void agregarMensaje(String texto){
        jTextArea1.append(texto);
    }

    public void agregarMensajeChat(Message mensaje){
        textAreaChat.append(mensaje.emisor + ": " + mensaje.mensaje + "\n");
    }

    public void dibujarTablero(Board tablero){
        BoardDrawer creadorTablero = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), getCasillasDibujadas(), tablero);
        creadorTablero.dibujarTablero();
    }

    public void dibujarPiezas(int[] posiciones, Pieza[] piezas, String[] nombres){
        ArrayList<Pieza> piezasArrayList = new ArrayList<>(Arrays.asList(piezas));
        for (int i = 0; i<piezasArrayList.size(); i++){
            //dibujarPieza(posicion[i], pieza[i], nombre[i])
        }
    }

    public void dibujarPiezaPropia(int posicion, Pieza pieza, String nombre){
        //System.out.println("Pieza dibujada propia");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        boardDrawer.dibujarPiezaEnClientePropio(punto, pieza);
    }

    public void moverPiezaPropiaExistente(int posicion, Pieza pieza, String nombre){
        //System.out.println("Pieza movida");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        boardDrawer.moverPiezaExistente(punto, pieza.getLabel());
    }

    public void dibujarPiezaOtroCliente(int posicion, Pieza pieza, String nombre){
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        JLabel label = boardDrawer.dibujarPiezaEnServer(punto, pieza);
        //Agregar al array de labels existentes serverside
        int indice = cliente.getNombresOtrosPlayers().indexOf(nombre);
        cliente.getLabelsOtrosPlayers().set(indice, label);
        //System.out.println("Label de otro player agregado");
    }

    public void moverPiezaExistenteOtroCliente(int posicion, Pieza pieza, String nombre){
        //System.out.println("Pieza movida otro player");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        JLabel label = cliente.obtenerLabel(nombre);
        boardDrawer.moverPiezaExistente(punto, label);
    }

    public void actualizarEstadoBotonTirada(boolean estuTurno) {
        jButton1.setEnabled(estuTurno);
        if (estuTurno) {
            agregarMensaje("¡Es tu turno! Puedes lanzar los dados.\n");
        } else {
            agregarMensaje("Es el turno de otro jugador. Espera tu turno.\n");
        }
    }

    public void actualizarLabelDados(int dado, String texto){
        if (dado == 0){
            labelRDado1.setText(texto);
        } else{
            labelRDado2.setText(texto);
        }
    }

    public void actualizarLabelDadosTotal(int total){
        labelRDadoTotal.setText(total + "");
    }
    

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void enviarMensajeChat(){
        Message mensaje = new Message("mensajeChat", cliente.getNombre(), "todos", textFieldChat.getText());
        cliente.escribirMensaje(mensaje);
    }

}
