/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Client.Cliente;
import Models.Board;
import Models.Message;
import Models.MessageRequest;
import Models.Pieza;

import java.awt.Point;
import java.util.ArrayList;
import java.util.Arrays;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 23jic
 */
public class ClientFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientFrame.class.getName());
    private Cliente cliente;
    private int casillasDibujadas;
    private final int sizeCasilla = 30;
    
    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        
        initComponents();
        cliente = new Cliente(this);
        //cliente.solicitarPiezasDisponiblesServer();
        jTextArea1.append(cliente.getNombre());
        jButton1.setEnabled(false); // Disable the button until it's the player's turn
        //cliente.getPlayer().setPieza(obtenerPieza());
        //cliente.eliminarPiezaSeleccionada();
        //cliente.enviarPiezasDisponiblesActualizadas();
        //TODO: Eliminar pieza de las piezas disponibles en server
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonPieza = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jButton1.setText("Tirar dados");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButtonPieza.setText("Seleccionar pieza");
        jButtonPieza.addActionListener(this::jButtonPiezaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPieza)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPieza)
                        .addGap(21, 21, 21))))
        );

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!cliente.isTurnoActual()) {
            JOptionPane.showMessageDialog(this, "No es tu turno aún. Espera a que el servidor te notifique.");
            return;
        }
        cliente.realizarLanzamientoDeDados();
        if (cliente.getPlayer().getPieza().getLabel() == null){
            dibujarPiezaPropia(cliente.getPlayer().getPosicion(), cliente.getPlayer().getPieza(), cliente.getNombre());
        }
        else{
            moverPiezaPropiaExistente(cliente.getPlayer().getPosicion(), cliente.getPlayer().getPieza(), cliente.getNombre());
        }
        //TODO: Identificar casilla en la que cae, postear mensaje indicando
        cliente.checkCasillaActual();
        
        //dibujarTablero(cliente.getTablero());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiezaActionPerformed
        // TODO add your handling code here:
        obtenerPieza();
        
    }//GEN-LAST:event_jButtonPiezaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPieza;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables


    public String obtenerNombre(){
        String name = JOptionPane.showInputDialog("Digite su nick:");
        return name;
    }

    public void obtenerPieza(){
        String nombrePieza = (String) JOptionPane.showInputDialog(null, "Escoja una pieza para jugar:", "Pieza", JOptionPane.QUESTION_MESSAGE, null, cliente.obtenerStringPiezasDisponibles(), cliente.obtenerStringPiezasDisponibles()[0]);
        if (nombrePieza != null){
            Pieza piezaSeleccionada = cliente.obtenerPiezaDesdeString(nombrePieza);
            if (cliente.getPlayer().getPieza() != null){
                //Pieza vuelve a ser disponible
                cliente.getPlayer().getPieza().setDisponible(true);
                cliente.habilitarPiezaSeleccionada();
            }
            cliente.getPlayer().setPieza(piezaSeleccionada);
            cliente.deshabilitarPiezaSeleccionada();
            cliente.enviarPiezasDisponiblesActualizadas();
            cliente.enviarMensajeATodos("El jugador " + cliente.getNombre() + " ha escogido la pieza " + cliente.getPlayer().getPieza().getNombre());
        }
        
    }
    
    public void agregarMensaje(String texto){
        jTextArea1.append(texto);
    }

    public void dibujarTablero(Board tablero){
        BoardDrawer creadorTablero = new BoardDrawer(jPanel1, sizeCasilla, casillasDibujadas, tablero);
        creadorTablero.dibujarTablero();
    }

    public void dibujarPiezas(int[] posiciones, Pieza[] piezas, String[] nombres){
        ArrayList<Pieza> piezasArrayList = new ArrayList<>(Arrays.asList(piezas));
        for (int i = 0; i<piezasArrayList.size(); i++){
            //dibujarPieza(posicion[i], pieza[i], nombre[i])
        }
    }

    public void dibujarPiezaPropia(int posicion, Pieza pieza, String nombre){
        System.out.println("Pieza dibujada propia");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, sizeCasilla, 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        boardDrawer.dibujarPiezaEnClientePropio(punto, pieza);
    }

    public void moverPiezaPropiaExistente(int posicion, Pieza pieza, String nombre){
        System.out.println("Pieza movida");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, sizeCasilla, 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        boardDrawer.moverPiezaExistente(punto, pieza.getLabel());
    }

    public void dibujarPiezaOtroCliente(int posicion, Pieza pieza, String nombre){
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, sizeCasilla, 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        JLabel label = boardDrawer.dibujarPiezaEnServer(punto, pieza);
        //Agregar al array de labels existentes serverside
        int indice = cliente.getNombresOtrosPlayers().indexOf(nombre);
        cliente.getLabelsOtrosPlayers().set(indice, label);
        System.out.println("Label de otro player agregado");
    }

    public void moverPiezaExistenteOtroCliente(int posicion, Pieza pieza, String nombre){
        System.out.println("Pieza movida otro player");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, sizeCasilla, 0, cliente.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        JLabel label = cliente.obtenerLabel(nombre);
        boardDrawer.moverPiezaExistente(punto, label);
    }

    public void actualizarEstadoBotonTirada(boolean estuTurno) {
        jButton1.setEnabled(estuTurno);
        if (estuTurno) {
            agregarMensaje("¡Es tu turno! Puedes lanzar los dados.\n");
        } else {
            agregarMensaje("Es el turno de otro jugador. Espera tu turno.\n");
        }
    }

}
