/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.Border;

import Models.Tablero.Board;
import Models.Tablero.Casilla;
import Models.Tablero.Pieza;
import Models.Messages.MessageBoard;
import Models.Messages.MessageRequest;
import Server.Server;

import java.awt.Color;
import java.awt.Point;

/**
 *
 * @author 23jic
 */
public class ServerFrame extends BoardFrame {
    private Server server;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerFrame.class.getName());

    /**
     * Creates new form ServerFrame
     */
    public ServerFrame() {
        initComponents();
        server = new Server(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelNClientesConectados = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        buttonNextTurn = new javax.swing.JButton();
        buttonOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Clientes conectados:");

        jButton1.setText("Comenzar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        labelNClientesConectados.setBackground(new java.awt.Color(0, 0, 0));
        labelNClientesConectados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNClientesConectados.setForeground(new java.awt.Color(255, 255, 255));
        labelNClientesConectados.setText("NCC");

        jButton2.setText("Crear Tablero");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        buttonNextTurn.setText("Siguiente turno");
        buttonNextTurn.addActionListener(this::buttonNextTurnActionPerformed);

        buttonOrden.setText("Obtener orden");
        buttonOrden.addActionListener(this::buttonOrdenActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNClientesConectados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonOrden)
                                .addGap(18, 18, 18)
                                .addComponent(buttonNextTurn)))
                        .addGap(0, 72, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(labelNClientesConectados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOrden)
                    .addComponent(buttonNextTurn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        server.getThreadConexiones().start();
        server.inicializarTurno();
        jTextArea1.setText("Iniciado");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Board tablero = new Board();
        server.setTablero(tablero);
        agregarMensaje("Tablero creado");
        dibujarTablero(tablero);
        server.broadcast(new MessageBoard("board", "server", "all", "tablero", tablero));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextTurnActionPerformed
        // TODO add your handling code here:
        server.siguienteTurno();
    }//GEN-LAST:event_buttonNextTurnActionPerformed

    private void buttonOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdenActionPerformed
        // TODO add your handling code here:
        //Determinar orden de jugadores y mostrarlo en pantalla
        /*Después de seleccionar una ficha o personaje, cada jugador debe escribir un número entre 1 y 1000.   
        El juego gererará un aleatorio entre 1 y 1000. El jugador que se acerque más al número aleatorio jugará de primero, 
        el segundo más cercano de segundo, así el tercero y cuarto y sucesivamente. 
        En caso de empate, en el orden que esté en la estructura de datos que representan la lista de jugadores.
        2. Cada jugador lanzará 2 dados. El orden estará determinado por el valor obtenido en los dados, el mayor será el primero, 
        el menor el último. Empates se determinan con la posición en lista */

        //Establecer metodo de orden aleatoriamente
        int metodo = (int) (Math.random() * 2) + 1; //1 o 2
        server.setMetodoOrden(metodo);
        if (metodo == 1) {
            //Enviar mensaje a clientes para que escriban un número entre 1 y 1000
            server.broadcast(new MessageRequest("request", "server", "all", "Escriban un número entre 1 y 1000", "numero_orden"));
            agregarMensaje("Orden de juego determinado por número entre 1 y 1000");
        } else {
             //Enviar mensaje a clientes para que lancen dados
            server.broadcast(new MessageRequest("request", "server", "all", "Lancen los dados para determinar el orden de juego", "lanzar_dados"));
            agregarMensaje("Orden de juego determinado por lanzamiento de dados");
        }
        

    }//GEN-LAST:event_buttonOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNextTurn;
    private javax.swing.JButton buttonOrden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelNClientesConectados;
    // End of variables declaration//GEN-END:variables

    public void agregarMensaje(String texto){
        jTextArea1.append(texto);
    }

    public void actualizarLabelClientes(String cantidadClientes){
        labelNClientesConectados.setText(cantidadClientes);
    }

    public void dibujarTablero(Board tablero){
        BoardDrawer creadorTablero = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), getCasillasDibujadas(), tablero);
        creadorTablero.dibujarTablero();
    }
    
    public void dibujarPieza(int posicion, Pieza pieza, String nombre){
        //System.out.println("Pieza dibujada");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), 0, server.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        JLabel label = boardDrawer.dibujarPiezaEnServer(punto, pieza);
        //Agregar al array de labels existentes serverside
        int indice = server.getNombresPlayers().indexOf(nombre);
        server.getLabelsPlayers().set(indice, label);
    }

    public void moverPiezaExistente(int posicion, Pieza pieza, String nombre){
        //System.out.println("Pieza movida");
        BoardDrawer boardDrawer = new BoardDrawer(jPanel1, getAnchoCasilla(), getAltoCasilla(), 0, server.getTablero());
        Point punto = boardDrawer.obtenerPuntoNumeroCasilla(posicion);
        JLabel label = server.obtenerLabel(nombre);
        boardDrawer.moverPiezaExistente(punto, label);
        //mover label del array de labels segun indice de nombre
    }

    
}
